### ISSUE TITLE
Catalina

### ISSUE THREAD

**Issue by mrgooge** [ali-rantakari/setWeblocThumb#2]
Just a shot in the dark here...
I get this error when run on MAC OS X Catalina: 

**setWeblocThumb: Bad CPU type in executable**

any ideas, I imagine this project maybe dead
but thanks

**Comment by yannickBurky** [comment]
Yes, unfortunately. Applications must be encoded under 64 bits to be compatible.

I'm also waiting for someone to update the code... 🙏

**Comment by mrgooge** [comment]
Wish I knew C!
